### ISSUE TITLE
Mreg error

### ISSUE THREAD

**Issue by AuroreAA** [Mufabo/Rrobustsp#2]
Dear @Mufabo,

Thank you very much for your hard work for putting available the robustSP tool in R!

However, I just wanted to let you know that I encounter an issue with the computation of the M-estimates of regression using IRWLS algorithm (`Mreg()`). Indeed, when I use a matrix for `X` , I have the following error: `Error in if (class(X) == "matrix") { : the condition has length > 1`, it is because in fact a matrix is also an array and so your equality check returns an error. 

Here is an example, which compared the `hubreg()` and `Mreg()` functions:
`> y <- c(1.0347, 0.7269, -0.3034, 0.2939, -0.7873)
> X <- matrix(c(0.884, -1.1471, -1.0689, -0.8095, -2.9443, 1.4384, 0.3252, -0.7549, 1.3703, -1.7115), 5, 2)
> class(X)
[1] "matrix" "array" 
> hubreg(y, X)
[[1]]
            [,1]
[1,] -0.03334926
[2,]  0.51537127

[[2]]
[1] 0.5184239

[[3]]
[1] 1

> Mreg(y, X)
Error in if (class(X) == "matrix") { : the condition has length > 1`

Thank you again!

**Comment by Mufabo** [comment]
Hi, thanks for the bug report. I'll try to fix it asap.

**Comment by AuroreAA** [comment]
Thank you very much!

**Comment by Mufabo** [comment]
@AuroreAA I've just pushed the latest version. Your given example works now, the results matched those of the matlab toolbox (https://github.com/RobustSP/toolbox). 

Please confirm if it also works for you.

**Comment by AuroreAA** [comment]
@Mufabo, thank you very much, everything is working well now!
